### ISSUE TITLE
Enhancement request 

### ISSUE THREAD

**Issue by sajanv88** [mrvautin/expressCart#101]
Hello, 
I read your contribution's information I'd suggest to use Next js rather vue.js. Nextjs is more popular and by default it offers SSR and other cool features. I am happy to contribute if we agree to go-head with Nextjs.

**Comment by mrvautin** [comment]
I've been trying to fix up the API so a good framework can be used for the admin side of things. I'm not sure I've got 100% coverage on the admin endpoints yet. I'm still not sold on Next, Vue etc as a good solution for a shopping cart customer side functionality.

**Comment by sajanv88** [comment]
@mrvautin  Can you please list down some of the issues or improvements that you want do? I believe I can think of more ideas or maybe it will be a good starting point for me to contribute in this project. Will you?

**Comment by mrvautin** [comment]
I don't really have a plan for new functionality. I'm currently just trying to decouple the admin UI/backend by creating API endpoints for all functionality so a more modern UI component can be used - eg: Vue, React etc.

I'm open to any new functionality or improvements you suggest from the actual cart perspective.

**Comment by amarwali** [comment]
I want to add cash on delivery option instead of PayPal or other payment methods.
Can you help ?

**Comment by mrvautin** [comment]
There is already an "instore" option. See the docs.

**Comment by amarwali** [comment]
One other problem I am facing is that if one product of size small is
selected and the same product in large is also selected the cart does not
recognize it. The cart will show 2 products in S not 1 S and 1 L.

**Comment by mrvautin** [comment]
Yes that is an issue. Can you raise a seperate issue for this?

**Comment by amarwali** [comment]
Should i write this on your GitHub repository?

**Comment by mrvautin** [comment]
Yes. Raise an issue on this repo.

**Comment by mrvautin** [comment]
Fixed in #110.
