### ISSUE TITLE
Enhancement For admin page

### ISSUE THREAD

**Issue by mammadjafar** [mrvautin/expressCart#102]
Consider adding some configuration option to hide helper infos in admin page. Check the screenshot..

![Screen Shot 2019-12-02 at 4 01 40 PM](https://user-images.githubusercontent.com/24502055/69969951-ab46cc00-151d-11ea-9cae-9f6c186345c4.png)

**Comment by mrvautin** [comment]
Thanks for your suggestion. I've considered it but feel this is of little benefit and will leave it as is.
