### ISSUE TITLE
 I have successfully created an order but haven't seen the payment function (or login) when checking the shopping cart.

### ISSUE THREAD

**Issue by Nghiait123456** [mrvautin/expressCart#105]
@mrvautin  - Hello. I have successfully created an order but haven't seen the payment function (or login) when checking the shopping cart. I have yet to find it in read me and code. Can you show me about it. Thanks very much
![Screenshot from 2019-12-23 13-22-35](https://user-images.githubusercontent.com/40486925/71340004-e8840400-2587-11ea-91f4-d43f8a369fe1.png)

**Comment by mrvautin** [comment]
You need to click the “checkout” button and follow the process.
