### ISSUE TITLE
Info request: admin orders

### ISSUE THREAD

**Issue by gmadhusureshn** [mrvautin/expressCart#106]
Thank you for putting great application Mrvautin appreciate your help.
Looking for following info
1. Is there any plan for creating custom orders form admin panel?
2. Is there any option to by pass payment gateway
3. Dash board for orders placed, sold etc

**Comment by mrvautin** [comment]
1. I'm not sure. Can you explain this further?
2. This is not on my radar. What would the use case for this?
3. This sounds like a good idea.

**Comment by gmadhusureshn** [comment]
Thank you for getting back to me  Mrvautin. Happy New year
1. Lets say business contains physical store and  online presence. when the customers walks in admin should be able to place an order
2. Some times customers want to pay in cash when they walk into store
3. Thank you

**Comment by mrvautin** [comment]
I've added point 2 in commit eafb690445db2b5d2eba1bfcff884ff5f5cbfa78.
I've added point 3 in commit 7cef58dae3ad180afb73530288f306a9d1771bd3.

**Comment by gmadhusureshn** [comment]
Awesome Mrvautin.. you are the best
Closing the issue

**Comment by mrvautin** [comment]
Point 3 has now been added in the latest commit.
