### ISSUE TITLE
Unable to login with credentials

### ISSUE THREAD

**Issue by n-jay** [mrvautin/expressCart#111]
Once the `npm start --production` has been run and the server is deployed locally, any attempts to login via the default credentials fail.
Thereafter I tried changing the provided credentials on mongodb to something simpler, and the issue still persists.
The new admin credentials are shown in the below image.
![image](https://user-images.githubusercontent.com/24616975/72682770-b6b67c80-3af6-11ea-8b16-fbcf17620e14.png)

The error that pops up when the new credentials are tried on the login screen.
![image](https://user-images.githubusercontent.com/24616975/72682796-1ad94080-3af7-11ea-962e-8fcdc655161d.png)
The issue persists when login is attempted with the non-admin account as well.

Please forgive me if I'm overlooking an obvious issue. I'm extremely new to development on node.

**Comment by mrvautin** [comment]
It doesn't work like this. You cannot simply add a plaintext password as the login route is expecting a hash of that password. 

You would be better off resetting the password for the admin user via `/admin/users`

**Comment by n-jay** [comment]
Noted @mrvautin.
Thank you for the swift response!
