### ISSUE TITLE
Issue in payment with stripe

### ISSUE THREAD

**Issue by abhay2701** [mrvautin/expressCart#117]
Stripe Checkout can't communicate with our payment processor because the API key is invalid. Please contact the website owner or support@stripe.com.

**Comment by mrvautin** [comment]
Sounds like the Stripe API key you are using is invalid. Check the API key in the `.json` settings file.

**Comment by abhay2701** [comment]
in settings.json i have to check? or stripe.json?

**Comment by abhay2701** [comment]
I have generated the api key but what does this line means " Once an API Key is generated it will need to be supplied in a header called `apiKey` to authenticate requests."

**Comment by mrvautin** [comment]
stripe.json. Just replace the values with real ones from the Stripe dashboard.

**Comment by abhay2701** [comment]
Thankyou so much, I solved it.
