### ISSUE TITLE
Error is coming while adding new product

### ISSUE THREAD

**Issue by abhay2701** [mrvautin/expressCart#118]
schemaValidate errors [ { keyword: 'format',
    dataPath: '.productPrice',
    schemaPath: '#/properties/productPrice/format',
    params: { format: 'amount' },
    message: 'should match format "amount"' } ]

**Comment by mrvautin** [comment]
What price are you entering? You need to enter a full 2 decimal amount. Eg: `1.00` and not simply `1`.

**Comment by abhay2701** [comment]
Yes, it's working thankyou.
