### ISSUE TITLE
Why product description can't add youtube video?

### ISSUE THREAD

**Issue by joeywu321** [mrvautin/expressCart#119]
I have tried 2 way to do this.

1. I chose "insert video", and type youtube video url inside it.
2. I use "code view", and type iframe html tag that youtube webpage recommend.

Both way can't save the result.
Is there any way to show video in "product description"?

**Comment by joeywu321** [comment]
No use.
After save product, the result html still can't see video.
Only an empty frame.

**Comment by mrvautin** [comment]
Are you able to post the HTML you are trying to add?

I've tested the following and it works fine:
``` html
<iframe width="560" height="315" src="https://www.youtube.com/embed/oHg5SJYRHA0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by joeywu321** [comment]
Before
<img width="2108" alt="截圖 2020-02-21 下午12 52 44" src="https://user-images.githubusercontent.com/12403518/75005422-5d50bd00-54a9-11ea-8969-3f43e90f61e8.png">

After(Save Product)
<img width="2132" alt="截圖 2020-02-21 下午12 53 05" src="https://user-images.githubusercontent.com/12403518/75005411-4f02a100-54a9-11ea-9662-7582dbb2a22b.png">

**Comment by mrvautin** [comment]
Can you try not using the code view button and paste the HTML into the Markdown editor?

**Comment by joeywu321** [comment]
I don't understand.
How to write html without using code view button?

**Comment by mrvautin** [comment]
Just using the regular markdown view. I'm able to enter HTML without issue.

![image](https://user-images.githubusercontent.com/299398/75007427-05c04a80-54c5-11ea-922f-4449042790f2.png)

**Comment by joeywu321** [comment]
Oh,
It's OK.
Thank you.
