### ISSUE TITLE
New Feature Request - Customer Account Page

### ISSUE THREAD

**Issue by acidrs03** [mrvautin/expressCart#123]
Hello,
         I think a good feature to add to this project would be a Customer account page. A customer can login and be able to view the status of their orders. The page would show the order number and order details with an order status like, Processing, shipped, completed etc. These status can be configured in the admin page so that you can setup as many status types as you like.

**Comment by mrvautin** [comment]
Good idea. I think this would be a good addition. I will add to the backlog unless someone would like to pick this up and run with it?

**Comment by mrvautin** [comment]
Starting in #124

**Comment by mrvautin** [comment]
Implemented in 78e06e511b4a985151369f320ddf3ee65e1a4cd4.
