### ISSUE TITLE
trackStock application crash

### ISSUE THREAD

**Issue by amarwali** [mrvautin/expressCart#125]
If track stock is true, after place order the website shows error.
If stock = 0, the cart still adds that product once

**Comment by mrvautin** [comment]
Works for me. Can you give more information? Your settings file etc?

**Comment by amarwali** [comment]
We can not set stock for different sizes.
If track stock is = 1, medium-size and large size both can be get added one by one for multiple times

**Comment by amarwali** [comment]
If trackstock = true and stock level is set to 1.
We can add 1 product multiple times to our shopping cart. And the cart count will increase.
It just doesn't allow to add more than 1 at the same time.

**Comment by mrvautin** [comment]
> We can not set stock for different sizes.
If track stock is = 1, medium-size and large size both can be get added one by one for multiple times

This is a feature. Stock is based on the product as a whole and not with the options. Possibly one day options will be expanded out to have their own stock control. Right now, stock control is at a very basic level for the whole product.

**Comment by mrvautin** [comment]
> If trackstock = true and stock level is set to 1.
We can add 1 product multiple times to our shopping cart. And the cart count will increase.
It just doesn't allow to add more than 1 at the same time.

There is a bug but hopefully fixed in 9079509c42a5747b9f86a0c2a91be7ae1da031fd.
