### ISSUE TITLE
Test data cannot be inserted while using docker

### ISSUE THREAD

**Issue by happyhardik** [mrvautin/expressCart#132]
1. I am using Docker version of expressCart on my local system.
2. In the DockerFile you are not copying the "test" folder. (I manually added it for myself)
3. When I try to run `npm run testdata` from the node container, it fails as the application is already running and using the port. I haven't gone into more details, but this seems to be happening because, in testdata.js you are importing `../test/helper` which is requiring app.js.
In my case, I manually stopped the application and inserted test data and restarted the application manually, which did the trick for me.

**Comment by mrvautin** [comment]
I'm not a Docker use and didn't setup the original Docker changes. Are you able to have a look into this further and possibly fix? Maybe someone else can help too?

**Comment by happyhardik** [comment]
This issue is been taken care of by me in #145
