### ISSUE TITLE
There is no way to sort the products

### ISSUE THREAD

**Issue by happyhardik** [mrvautin/expressCart#133]
As there is no way to sort the products in the frontend, I was working on implementing it. 
Now there are a few questions about the implementation:
1. Should it be implemented as a global parameter alongside the search or should be in the (template) body with the filtered keyword, so that it can work with searched result as well. I think when you have a lot of products, it would be useful.
2. What kind of sort features should be available, the ones that I have in mind are Price: low-to-high, Price: high-to-low, Popular and Featured.
3. For sorting by popular, we will have to either use the number of orders or better save the number of product views and bring up the popular ones.
4. For featured, we will have to give users an option to make a product featured. This is useful when you have 10 important products and others are like accessories. Then you want to sort by featured products by default.

Let me know your thoughts.

**Comment by mrvautin** [comment]
There is a way to do simple sorting. Check the `productOrderBy` and `productOrder` setting in the `config/settings.json` file.

I’m open to expanding on this to make it a bit clever. Your suggestions sound really good.

**Comment by happyhardik** [comment]
Sure, I am happy to give a helping hand.
