### ISSUE TITLE
The option to track stock isn't showing on new or edit product pages.

### ISSUE THREAD

**Issue by andrew-lovato** [mrvautin/expressCart#135]
I am not sure how to turn on/activate the track stock option. When I load the new products page, there is no input for stock or for activate/deactivate the tracking. same with Edit page.

**Comment by mrvautin** [comment]
You need to turn it on in the `settings.json` file. There is an example in the readme and it’s disabled by default.

**Comment by andrew-lovato** [comment]
Thank you for the response, found the section to make the change!
