### ISSUE TITLE
There is no way to connect stock with size

### ISSUE THREAD

**Issue by andrew-lovato** [mrvautin/expressCart#136]
I want to be able to connect my stock with specific sizes. Say I have a shirt design with 5 different sizes. I'd need to be able to track the stock of each size. It seems I can only track the total stock of all shirts.

**Comment by mrvautin** [comment]
This is a know limitation of the stock option. An alternative (which is not ideal) is adding a product for each size.

**Comment by andrew-lovato** [comment]
gotcha, makes sense. I'm kind of a webdev- medium noob. Is it possible to use the "product options" to connect the size to the stock? I am not sure how to access the 'product options' object because there is only a single value pair and the array is made up of 'object', 'string','null' could I connect one of those to the stock?

**Comment by mrvautin** [comment]
I think an easy way would be to add products with a title of "Woollen Jumper - Small" and "Woollen Jumper - Large" and allow customers to buy either product. You can then add your stock of each size to the two products. 

Maybe I'm not understanding your problem?

**Comment by andrew-lovato** [comment]
You're totally understanding the problem. I am just looking for a way to avoid duplicating products in the index view. Thank you for your help, I appreciate it.

**Comment by mrvautin** [comment]
Yeah I can see that. I think the whole product options would need to be looked at to properly cater for stock per option. Hopefully someone might help pick this up.

**Comment by mrvautin** [comment]
Hi @andrew-lovato I've been working on this in PR #139. Can you have a look and let me know what you think?

**Comment by andrew-lovato** [comment]
I'll be honest the code is a bit beyond me, but I mostly understand it and thank you so much for including the change. it looks great!

**Comment by mrvautin** [comment]
This has now been merged.
