### ISSUE TITLE
HTTPS expresscart

### ISSUE THREAD

**Issue by hendryt** [mrvautin/expressCart#137]
How can I configure my install of express-cart to run as HTTPS server?
I cannot integrate with Stripe without being on HTTPS

**Comment by mrvautin** [comment]
expressCart is just the app. You will need to run you own web server like Nginx or Apache and buy an SSL cert or use Letsencrypt for a free one. 

There are plenty of guides to setup a Nodejs app on either web server type.

**Comment by hendryt** [comment]
thank you
