### ISSUE TITLE
Cannot delete item from Cart 

### ISSUE THREAD

**Issue by EngMohamedNor** [mrvautin/expressCart#138]
Cannot delete item from Cart it shows : Product not found in cart

and if you refresh the item is still in the cart

**Comment by mrvautin** [comment]
Could you give more information? The steps, anything logged in the browser console, Node console, what product etc? Can you also confirm you are running the latest version. This was an old bug which should be fixed.

**Comment by EngMohamedNor** [comment]
Also checked in the demo app here : https://demo.expresscart.markmoffat.com/ same issue

1. add one product to cart
2. add another product to cart (Different product)
3. try to remove the first item from the cart

THIS SHOWS : Product not found in cart

(Quite strange : sometimes its ok )

One other case : 
1. add two items in cart.
2. delete one of them
3. close shopping cart or go to another link (page reload needed)
4. try to open the cart and delete the item 

THIS SHOWS : Product not found in cart (red popup)

Hope this helps diagnose the problem 
tested now with the online demo app.

**Comment by mrvautin** [comment]
Fixed in 73783eca876ac3761f7e3f64eaeb2a2d66899a3c.
