### ISSUE TITLE
Reduce country list

### ISSUE THREAD

**Issue by amarwali** [mrvautin/expressCart#143]
There are a lot of countries, when selecting countries in the customer information section! How to add fewer countries in the list?

**Comment by mrvautin** [comment]
You can edit the list here or provide your own list/array of countries:

https://github.com/mrvautin/expressCart/blob/82753996c03f2e52d560609a2f3a418accf1a17b/lib/common.js#L18

**Comment by amarwali** [comment]
Thank you for your response
