### ISSUE TITLE
The common.js file is getting too big

### ISSUE THREAD

**Issue by happyhardik** [mrvautin/expressCart#146]
This is kind of a suggestion, the common.js file is getting bigger and we are just getting started.
It would be a good idea to introduce a controllers folder (following a typical MVC pattern), where we divide the code into a specific controller based on what it does. Something like auth controller, cart controller, products controller etc.

**Comment by mrvautin** [comment]
I agree but I don't think having a file for each is function is required like MVC but I agree some logical grouping could be done to reduce the file size and make them more workable.

**Comment by mrvautin** [comment]
@happyhardik Could you please review the PR #150?

**Comment by happyhardik** [comment]
Done!

**Comment by happyhardik** [comment]
One more suggestion while this is open, I see the readme file is also getting bigger and hard to find what you need.
Here are some suggestions: 
- I see that we need to expand the API documentation and it can take a separate section
- The main readme file can have installation and usage guide, while we can have a separate section for developers
- We need to have a guide for theme development. I was thinking about it if I want to develop a new theme other than the default "CLOTH", where should I start?

Let me know your thoughts.

**Comment by mrvautin** [comment]
Sorry, missed this. Your suggestions sound good. Do you want to make a start?

**Comment by happyhardik** [comment]
Yes, sure!

**Comment by happyhardik** [comment]
Should I use the GitHub.com Wiki feature for documentation or you have something else in mind?
We can also start by creating a docs folder in the repo and add some docs in there.
