### ISSUE TITLE
Product variants not displaying on home page

### ISSUE THREAD

**Issue by tellus-git** [mrvautin/expressCart#148]
Tried out your shopping cart and I would say its one of the best. Easy and simple to use, both for the customer and vendor.

Variants are being shown on the product description page when the add to cart button is clicked. Is it possible to have the variants displayed on the home page itself. That way a step is reduced for the customer and the variant could be selected on the home itself.

**Comment by mrvautin** [comment]
This is not an issue but by design. The product link on the homepage will only take you to the full product when there are variants.

How do you envisage the homepage would look with variants? Can you provide an example or mock something up?

**Comment by tellus-git** [comment]
Thanks for the quick response. Agree that this is by design and not an issue. With the variants on home the customer would know that there are options for the product. 
An example of a site with variants on the homepage is https://www.bigbasket.com 
Another example from dmarts.in 
![image](https://user-images.githubusercontent.com/46710503/82113334-e149d680-9772-11ea-9b3d-5259be6c3f91.png)

**Comment by mrvautin** [comment]
Here is how the changes look. 
![image](https://user-images.githubusercontent.com/299398/82186464-12b8d280-992a-11ea-9297-d19212469014.png)

Its a toggle (defaults to off) in the `settings.json` file: `"showHomepageVariants": true`

**Comment by rodrigoricky** [comment]
![image](https://user-images.githubusercontent.com/89636767/136317332-e7140d82-9ce4-47f1-9172-b1564c28cc2d.png)
Got this error while trying to add a variant
