### ISSUE TITLE
sometimes Stripe  payment fails

### ISSUE THREAD

**Issue by basharam** [mrvautin/expressCart#15]
Sporadically stripe payment fails with message" your payment declined".

Both secret key and public key are test keys, with card number as 4242 4242 4242 4242.

Out of context, does  expresscart supports
1.  General user login instead admin/login.? say user purchased a product, and want to track his oders history on the stores.
2. right now I see anyone can be admin, on expresscart in what ways this can be restricted.

P.S. recently embarked in backend programming :)

**Comment by mrvautin** [comment]
That is something you would need to query with Stripe.

Currently it only supports a returning customers address etc. It doesn’t have any functionality to see and track orders. Maybe someone can add this?

Only certain users you setup can be admin. The rest are customer users.
