### ISSUE TITLE
Handle static files after deployment

### ISSUE THREAD

**Issue by amarwali** [mrvautin/expressCart#151]
Everything works perfectly and deployment the project on heroku is very easy, but static images disappears from the website after few minutes. Any solution to handle those?

**Comment by mrvautin** [comment]
Apparently Heroku doesn't persist files: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

I didn't know this until now so Heroku is likely not the best solution for exppressCart. I think Heroku is pretty crap if I'm honest. If I were you, I'd pick something like [Digital Ocean](https://m.do.co/c/cd185d01653f).

**Comment by amarwali** [comment]
Will digital ocean manage the static file automatically? With heroku we
need aws S3 bucket or we have to pay to use their ad-on bucketeer.

**Comment by mrvautin** [comment]
Digital Ocean is just a VPS meaning files will persist as normal. You can setup backups too if required.

**Comment by amarwali** [comment]
I will try it and let you know, i was testing heroku, its very easy to
deploy nodejs there. The only problem that i face was of static files.
Because of which i had to upload my product images in public folder on my
github repo manually and redeploy ever time for the images to stay
permanently.
