### ISSUE TITLE
having problem in creating a new customer account

### ISSUE THREAD

**Issue by codemarvel** [mrvautin/expressCart#152]
There is no option for creating a new customer account. '/customer/create' route is not working

**Comment by mrvautin** [comment]
Could you give more information? what error? Are you using the API or trying from the cart UI?

**Comment by codemarvel** [comment]
I am trying from the cart UI.

**Comment by mrvautin** [comment]
What error? I just tried on latest master and it’s working fine. Please provide steps and the error text/screenshot.

**Comment by codemarvel** [comment]
![error](https://user-images.githubusercontent.com/34676388/84561680-25c59380-ad6c-11ea-8b5e-a14487bb3330.JPG)

**Comment by mrvautin** [comment]
That’s expected. It’s a `POST` route not a `GET` route. 

Was there a link which took you there?

**Comment by codemarvel** [comment]
no i just wrote the path , since i didn't find any any link to add a new customer.

**Comment by mrvautin** [comment]
You can create a new customer when checking out. If "Create an account" is checked, a new customer is created. 

![image](https://user-images.githubusercontent.com/299398/84568440-a9a86b80-adbe-11ea-847f-d4ddf3697fb8.png)

**Comment by codemarvel** [comment]
Oh It's here.. But It would've been great if there was a direct 'create an account' link on home page..
