### ISSUE TITLE
New Feature Request - Multiple Payment Options

### ISSUE THREAD

**Issue by acidrs03** [mrvautin/expressCart#153]
Hello,
         I was thinking that a nice new feature might adding the ability to enable multiple payment options. For example being able to allow Paypal and Blocknomics etc. 
This would allow server owners to accept multiple payment options for stores.

**Comment by dk122809** [comment]
Hi i can help in this just briefly explain me about this.

**Comment by mrvautin** [comment]
This is now in master.
