### ISSUE TITLE
Error (connect-mongodb-session/index.js:75:17) to run npm start --production 

### ISSUE THREAD

**Issue by almilcargomez** [mrvautin/expressCart#157]
@mrvautin 
sorry, i have an error (connect-mongodb-session / index.js: 75: 17) when executing the command npm start --production, in expressCart

**Comment by acidrs03** [comment]
> @mrvautin
> sorry, i have an error (connect-mongodb-session / index.js: 75: 17) when executing the command npm start --production, in expressCart

Hi @almilcargomez ,
                                Do you have a Mongo Database running on localhost? If not you can follow the instructions for your os from their documentation guide [https://docs.mongodb.com/manual/installation/]
