### ISSUE TITLE
Cash on Delivery as payment method, need to add

### ISSUE THREAD

**Issue by arahman0715** [mrvautin/expressCart#161]
Cash on Delivery as payment method, need to add

**Comment by mrvautin** [comment]
Payment methods are modular. If you need it you are welcome to add it in a PR.

**Comment by amarwali** [comment]
arahman0715 Cash on delivery method is already added by the name of instore.

**Comment by arahman0715** [comment]
Thanks, I am thinking to do that in a PR, hopefully...

Regards,
Mustak Ahmed
Full Stack web Engineer @upwork
<https://www.upwork.com/freelancers/~01d09706f744974342>,
Node.js/Javascript/webrtc/aws Developer
...........................................
Contact me for IT consultancy/Software Development: Visit my profile Mustak
Ahmed
<https://www.upwork.com/freelancers/~01d09706f744974342>
