### ISSUE TITLE
MVC Pattern

### ISSUE THREAD

**Issue by MehtaManan07** [mrvautin/expressCart#164]
The model-View-Controller pattern is not followed here. I believe that should be followed in any project. And needs a bit of refactoring here

**Comment by MAJIDNISAR** [comment]
also it needs structure using API for all the data routes, so that an app can work off it.

**Comment by pate313373** [comment]
I really like your project @mrvautin, but why are you just closing valid critism?
Looks like they wanted to offer their help.....
@MehtaManan07 
@MAJIDNISAR
