### ISSUE TITLE
New Feature Request - Customer reviews

### ISSUE THREAD

**Issue by amarwali** [mrvautin/expressCart#166]
In my opinion, customer ratings and reviews can increase the chances of a sale. It is is one of the mandatory features for an e-commerce store. Add comment is already implemented but not working. Order complete error before thankyou page

**Comment by mrvautin** [comment]
Prefer to implement an external service as a plugin rather than re-inventing the wheel. Do you have a preference?

> Add comment is already implemented but not working

What are you referring to? The only comment functionality is on the whole order which flows into the Admin page.

**Comment by mrvautin** [comment]
Added product reviews in #172.
