### ISSUE TITLE
Register/Sigin links or button

### ISSUE THREAD

**Issue by basharam** [mrvautin/expressCart#17]
Hi There, 
Where does new users register on expresscart. the only possibility I have seen is on payment page, it asks registration details if old user or fill form to create new one. but how/where do the newly registered users login to read their purchases?

**Comment by mrvautin** [comment]
The customer login is more aimed at returning customers not having to re-enter their details, not about viewing existing orders.

As someone else has asked the same question before it seems this is what people want. Happy to accept any PR’s with this functionality or I will add it when time pemits.
