### ISSUE TITLE
Video of Setup

### ISSUE THREAD

**Issue by Domdev67** [mrvautin/expressCart#171]
I am having troubles setting it up so if it is possible could make showing how to set it up

**Comment by amarwali** [comment]
Are you talking about deployment?
or do you want to run it locally?

**Comment by Domdev67** [comment]
Deployment

**Comment by mrvautin** [comment]
If you can post the steps or errors you are having problems with I will update the documentation to clarify. I'm not keen or in the position to shoot any videos explaining the setup process.
