### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by sifeddine-oudani** [mrvautin/expressCart#178]
i have question about how to add ssl in this app expresscart which is an amazing and nice of mrvautin to share it .
thank you.

**Comment by Tobenna-KA** [comment]
You should be adding SSL to your server

**Comment by sifeddine-oudani** [comment]
i have vps  how to add ssl to vps ???

**Comment by Tobenna-KA** [comment]
You would have to SSH into your VPS. Try checking out letsencrypt you can install it on your server and attach it to the domain name.
