### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [mrvautin/expressCart#18]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module.	We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by mrvautin** [comment]
To be clear. I’m the owner of this repo and have not received any emails re security issues. I would happily address any which are found.

Please get in touch: markmoffat.com

**Comment by lirantal** [comment]
Thanks Mark.

Can you check your spam folder or something like that?
You should've received an invite from the HackerOne platform to join the conversation.
