### ISSUE TITLE
Navbar is not Responsive

### ISSUE THREAD

**Issue by TGtarun** [mrvautin/expressCart#181]
Problems:
1). items present in the navbar are not responsive when the screen size is less than 990 px.
2). Dropdown button for switching languages will disappear when the screen size is reduced. (screen size < 557 px)

**Steps to Reproduce the behavior**
Open the application on mobile or on a small screen gadget.

**Actual Behaviour**

![responsive](https://user-images.githubusercontent.com/48594884/102689526-ccf81b80-4224-11eb-91fe-ebf9d705bc05.JPG)

**Comment by TGtarun** [comment]
@mrvautin I would like to work on this issue.

**Comment by mahmed0715** [comment]
+1

**Comment by mahmed0715** [comment]
@TGtarun any update on this?

**Comment by TGtarun** [comment]
@mahmed0715 yes now it is solved, check in PR

**Comment by mahmed0715** [comment]
![image](https://user-images.githubusercontent.com/2967789/102709290-61b95280-42d3-11eb-9bf0-93cffa3d990e.png)
the demo should reflect with the change?

**Comment by mrvautin** [comment]
Merged
