### ISSUE TITLE
[Design]Image does not adjust there size

### ISSUE THREAD

**Issue by TGtarun** [mrvautin/expressCart#182]
**Expected Behaviour**
Image height and width should be uniform throughout the row. Smaller images must fill the space given whereas larger images should fit in the given space.

**Actual behaviour**
In the attached Screenshot middle image does not fill the whole space like other images in the row.

![image_gap](https://user-images.githubusercontent.com/48594884/102690107-18acc400-4229-11eb-9a13-bbdb27fe6bc0.png)

**Comment by mrvautin** [comment]
Feel free to fix and I will merge.
