### ISSUE TITLE
[Documentation] Section for requirements

### ISSUE THREAD

**Issue by TGtarun** [mrvautin/expressCart#185]
Documentation should have a section that will tell about the installation of the required software. It need not be a detailed step by step guide but at least It may have links which will redirect the user to the respective sites. This section may act as a guide to a developer who doesn't have the setup ready.

**Comment by TGtarun** [comment]
Also, Documentation should clearly specify the deployment procedure on Heroku.

**Comment by TGtarun** [comment]
Now it has been resolved!. check in PR

**Comment by mrvautin** [comment]
What do you mean by this? The wiki has all the documentation and it's far easier to edit and maintain?
