### ISSUE TITLE
Docker has an error

### ISSUE THREAD

**Issue by hiwoobuy** [mrvautin/expressCart#192]
ERROR: Service 'expresscart' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat gulpfile.js: file does not exist

**Comment by hiwoobuy** [comment]
Solved.

**Comment by shuaichang** [comment]
Encountered the same error, seems gulpfile.js is not there, could you share how you solved the problem or simply removed. the COPY gulpfile.js ?
