### ISSUE TITLE
For Admin panel, username & password is not working 

### ISSUE THREAD

**Issue by Adcreators** [mrvautin/expressCart#200]
Admin User:
- User: demo@test.com
- Password: test

Gives a message email does not exist 
![Screen Shot 2021-02-16 at 2 25 28 pm](https://user-images.githubusercontent.com/62326194/108014829-e0780500-7062-11eb-82b8-8b57553a6588.png)

**Comment by mrvautin** [comment]
Fixed.

**Comment by Adcreators** [comment]
Thank you ..Admin is accessible now ...
