### ISSUE TITLE
Reverse Proxy Breaks Payment

### ISSUE THREAD

**Issue by Brandon4466** [mrvautin/expressCart#204]
Hello,

I have expressCart setup successfully and it works perfect on my local machine! It actually is really great!

The problem I ran into is once I put it behind a reverse proxy the payment breaks. When you get to the end payment screen (I use Stripe) the text boxes where you are supposed to enter the card number and expiration date doesn't show up, just the button that says process payment show up.

Have anyone experienced this before? Any suggestions of how I could go about fixing this?

I am using Windows Server 2019 running IIS. Everything works on the local machine via localhost.

Thank you so much for the help!!!

Sincerley,
Brandon

**Comment by meiremans** [comment]
Hello,

I don't have this issue. I'm running this on linux behind openresty though.

//edit: i have to say i have updated the stripe package, as the version currently in master didn't work for me. maybe that solves it?

**Comment by mrvautin** [comment]
Bumped Stripe version.
