### ISSUE TITLE
menu link

### ISSUE THREAD

**Issue by yonghing** [mrvautin/expressCart#21]
I create menu link http://127.0.0.1:1111/category/shoes
The first I clicked the link, the browser shows url http://127.0.0.1:1111/category/shoes (ok)
the second I clicked the link, the browser shows http://127.0.0.1:1111/category/category/shoes (error)
the third I clicked the link, the browser shows http://127.0.0.1:1111/category/category/category/shoes (error)

**Comment by mrvautin** [comment]
Can you be more specific? Which `theme` are you using?

**Comment by yonghing** [comment]
All the themes, giving same issue.

On 11 Jun 2018 6:27 AM, "Mark Moffat" <notifications@github.com> wrote:

Can you be more specific? Which theme are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrvautin/expressCart/issues/21#issuecomment-396087071>,
or mute the thread

**Comment by mrvautin** [comment]
It's due to your menu's being setup without a leading `/`.

**Comment by yonghing** [comment]
ok, is working now, thank you.

 regards,
 Paul Ho
