### ISSUE TITLE
Error if the length of the Permalink of product is set to 24

### ISSUE THREAD

**Issue by bulog** [mrvautin/expressCart#217]
After I add the Permalink of the product, and the length of it is 24

Then, expressCart try to parse the Permalink to the ObjectId.

Obviously Permalink is not the ObjectId.

Then the cart fail response.

the code at line 405 of file:
```/routers/index.js```

````
const product = await db.products.findOne({ $or: [{ _id: getId(req.params.id) }, { productPermalink: req.params.id }] });
````

and `/lib/common.js` 229
```
const getId = (id) => {
    if(id){
        if(id.length !== 24){
            return id;
        }
    }
    return ObjectId(id);
};
```

**Comment by bulog** [comment]
I tried to fix this by change the getId function at /lib/common.js 229

const getId = (id) => {
    if(id){
        if(id.length !== 24){
            return id;
        }
        if(!ObjectId.isValid(id)) {
            return id;
        }
    }
    return ObjectId(id);
};

**Comment by bulog** [comment]
tested, and it works

**Comment by mrvautin** [comment]
Yeah I don't think that function existed or was reliable when I wrote that code. I will fix in master repo.
