### ISSUE TITLE
when remove product options throws system error

### ISSUE THREAD

**Issue by yonghing** [mrvautin/expressCart#22]
when remove product options throws system error

cannot edit the product options ?

**Comment by mrvautin** [comment]
Sorry dude but you need to be more descriptive when raising issues. 

Eg: Include the system error and a bit more of a description on how to repeat the issue.

**Comment by yonghing** [comment]
regards,
 Paul Ho

**Comment by sloan58** [comment]
I think I know what he's talking about actually...  When removing product options in the admin panel the app will crash.  The error I get is something like

`mongodb/lib/utils.js:98     process.nextTick(function() { throw err; });`

I think I tracked it down to `routes/admin.js` and the `/admin/settings/option/remove` path.  I created PR https://github.com/mrvautin/expressCart/pull/25 for this.  I can get the options removed without crashing but the view needs a refresh to reflect the changes.

**Comment by mrvautin** [comment]
Fixed in #25 .
