### ISSUE TITLE
No Sign up / register page

### ISSUE THREAD

**Issue by rodrigoricky** [mrvautin/expressCart#237]
No Sign up / register page, I tried visiting /customer/create, but it says it doesn't exist, so technically there is no way for people to make their own account.

**Comment by meiremans** [comment]
On checkout it will ask you to make a password. if you fill that in and check the "create an account" checkbox it will make an account for that user

**Comment by rodrigoricky** [comment]
Hey there,

Thanks so much for reaching out! This auto-reply is just to let you know…

I received your email and will get back to you with a response as soon as possible. That's usually within a couple of hours. Evenings and weekends may take me a little bit longer.

If this is an urgent matter, you can message me on Facebook or please feel free to email me on my other account

I am looking forward to chatting with you!

Cheers,
Ricky
