### ISSUE TITLE
[Suggestion] A new CSS for the website

### ISSUE THREAD

**Issue by rodrigoricky** [mrvautin/expressCart#238]
I would like to suggest a different website design, not telling that the current is bad but it's a little bit simple yk, here's a reference website: gfxcomet.com

**Comment by meiremans** [comment]
the idea is that you make a theme yourself.
You can go to /views/themes and copy the Cloth directory and adapt it to your needs.

I guess it's kept simple on purpose because the more is in the default theme the harder it becomes for people to adapt it.
