### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by meiremans** [mrvautin/expressCart#239]
the default demo is not working

https://expresscart-demo.herokuapp.com/

**Comment by mrvautin** [comment]
Fixed.

**Comment by mingxin-yang** [comment]
@mrvautin demo is not working

**Comment by mrvautin** [comment]
Demo is here: https://expresscart-demo.markmoffat.com/

**Comment by mingxin-yang** [comment]
> Demo is here: https://expresscart-demo.markmoffat.com/

this is also not working

**Comment by mrvautin** [comment]
> > Demo is here: https://expresscart-demo.markmoffat.com/
> 
> this is also not working

It's definitely working for me. Define "not working".

**Comment by meiremans** [comment]
> 
> 
> > > Demo is here: https://expresscart-demo.markmoffat.com/
> > 
> > 
> > this is also not working
> 
> It's definitely working for me. Define "not working".

This also doesn't work for me.
NS_BINDING_ABORTED Firefox gives as result. 
My guess would be your firewall only allows your IP or something like that.

**Comment by mrvautin** [comment]
Fixed

**Comment by cx-andre-machado** [comment]
not working
