### ISSUE TITLE
Request:  Additive pricing for item options and free form item and order comments

### ISSUE THREAD

**Issue by aloupos** [mrvautin/expressCart#26]
I'm trying to purpose expressCart for online ordering platform for my restaurant (pickup/delivery), because the available commercial options lack flexibility.   The main difference between retail and food is optionality.  For example, if I order a hamburger, I might want to add cheese and bacon, both of which the restaurant would charge extra for.  This may also be useful for retail if an option might increase the price.  

The checkbox/radiobox concept works well here, because the options might be able to be combined, like in the hamburger example above, or they may be a single choice, like the size.  

Customers might also want to attach free-form comments to each item ordered, such as "No Ice please", or "Sauce on the side".  

Lastly, they may also want to add order level comments, like "Please call when you arrive".  

Lastly, thanks for creating expressCart ... it's really well thought out, and very useful to many.

**Comment by mrvautin** [comment]
Fixed in 9d94ea0a808ba6d6970d17dd090d54d647641bb6
