### ISSUE TITLE
Redirecting to /setup after creating new user

### ISSUE THREAD

**Issue by tesh254** [mrvautin/expressCart#31]
Hi mrvautin....I happen to have your previous model of the express cart and I run through the error where I can't  create a new admin user...any help would be appreciated. 
https://Mtush254.herokuapp.com

**Comment by mrvautin** [comment]
Not able to reproduce as the link doesn't work. I just downloaded a fresh install and seems to be working fine. Also, latest version has a bug fix around creation of initial user.
