### ISSUE TITLE
ERROR: for expresscart  no such image: 

### ISSUE THREAD

**Issue by michaelzbush** [mrvautin/expressCart#33]
Starting expresscart-mongodb ... done
Recreating expresscart       ... error

ERROR: for expresscart  no such image: sha256:1b0d52709e309e9384b7f40c07a2c65edce0b22bf7e4fda79728be769888c2d4: No such image: sha256:1b0d52709e309e9384b7f40c07a2c65edce0b22bf7e4fda79728be769888c2d4

ERROR: for expresscart  no such image: sha256:1b0d52709e309e9384b7f40c07a2c65edce0b22bf7e4fda79728be769888c2d4: No such image: sha256:1b0d52709e309e9384b7f40c07a2c65edce0b22bf7e4fda79728be769888c2d4
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN] y
....
....
expresscart-mongodb is up-to-date
Recreating bd9bb97161bc_expresscart ... done
Attaching to expresscart-mongodb, expresscart
expresscart    | 
expresscart    | > express-cart@1.1.10 start /var/expressCart
expresscart    | > node app.js
expresscart    | 
expresscart    | module.js:675
expresscart    |     throw err;
expresscart    |     ^
expresscart    | 
expresscart    | SyntaxError: /var/expressCart/config/settings.json: Unexpected string in JSON at position 829
expresscart    |     at JSON.parse (<anonymous>)
expresscart    |     at Object.Module._extensions..json (module.js:672:27)
expresscart    |     at Module.load (module.js:566:32)
expresscart    |     at tryModuleLoad (module.js:506:12)
expresscart    |     at Function.Module._load (module.js:498:3)
expresscart    |     at Module.require (module.js:597:17)
expresscart    |     at require (internal/module.js:11:18)
expresscart    |     at Object.<anonymous> (/var/expressCart/app.js:21:65)
expresscart    |     at Module._compile (module.js:653:30)
expresscart    |     at Object.Module._extensions..js (module.js:664:10)
expresscart    | npm ERR! code ELIFECYCLE
expresscart    | npm ERR! errno 1
expresscart    | npm ERR! express-cart@1.1.10 start: `node app.js`
expresscart    | npm ERR! Exit status 1
expresscart    | npm ERR! 
expresscart    | npm ERR! Failed at the express-cart@1.1.10 start script.
expresscart    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
expresscart    | 
expresscart    | npm ERR! A complete log of this run can be found in:
expresscart    | npm ERR!     /root/.npm/_logs/2018-11-03T19_34_06_469Z-debug.log
expresscart exited with code 1

-------------
Selecting "y", the expresscart app fails within both OSX and docker environments.

Thanks,
Michael

**Comment by mrvautin** [comment]
Can you post your settings.json with sensitive parts removed?
