### ISSUE TITLE
Porblems after change settings

### ISSUE THREAD

**Issue by tamircip** [mrvautin/expressCart#34]
Hey, first I would like to thank you for the great and beautiful code you built.
I just wanted you to know that when I updated the theme to "Material" it cannot start the app again and the error is "settings.json incorrect: data should NOT have additional properties".
In addition, most of the POST calls return a JSON file instead of AJAX elegant response.
Changing the "settings.json" back to the original fields fix it.
Besides, everything has worked for me in the meantime.
Thank you

**Comment by mrvautin** [comment]
Can you post your settings.json file?

The post calls should return valid JSON. Can you provide an example?

**Comment by tamircip** [comment]
settings.jon after chosse theme "Material":
`{
    "cartTitle":"xxxxxxx",
    "cartDescription": "website description",
    "cartLogo": "",
    "baseUrl": "http://localhost:1111",
    "emailHost": "smtp-mail.outlook.com",
    "emailPort": 587,
    "emailSecure": false,
    "emailUser": "xxxxxxxxxxxx@gmail.com",
    "emailPassword": "this_is_the_smtp_password",
    "emailAddress": "xxxxxxx@gmail.com",
    "menuEnabled": true,
    "flatShipping": 10,
    "freeShippingAmount": 100,
    "productsPerRow": 3,
    "productsPerPage": 6,
    "menuTitle": "Menu",
    "menuLocation": "side",
    "footerHtml": "",
    "googleAnalytics": "",
    "customCss": "",
    "currencySymbol": "$",
    "paymentGateway": "paypal",
    "databaseConnectionString": "xxxxxxxxxxxxxxx",
    "theme": "Material",
    "env": "",
    "themeViews": "../views/themes/Material/"
}`

I mean the POST requests redirect to the .json file and when I update something in the dashboard, it redirects to the .json file 
> // 20181104104651
> // http://localhost:1111/admin/settings/update
> 
> {
>   "message": "Settings successfully updated"
> }
> 
Instead of just show me a message in the bottom of the screen.
Restart the server make the error "settings.json incorrect: data should NOT have additional properties".
I've changed it back to the theme CLOTH from the dashboard and the json redirection has fixed but when start the app it is still makes the error.
Removing the "env" and the "themeViews" fields from the "settings.json" fix it all.

By the way, your code is written in  a very professional way. It's great to learn from it.
