### ISSUE TITLE
Where is defined the '/' route?

### ISSUE THREAD

**Issue by ealvizouri** [mrvautin/expressCart#35]
Hey, I'm new with express.js, maybe it's obvious, but I cannot locate the '/' route. I already googled, but there's nothing in stackoverflow.

**Comment by tamircip** [comment]
I'm pretty sure that the main route handled by the route 
`router.get('/:page?')`
and the 'page' is just nothing so it get back the index of the theme with the default order of products.

**Comment by mrvautin** [comment]
https://expressjs.com/en/guide/routing.html
