### ISSUE TITLE
product options don't show up correctly 

### ISSUE THREAD

**Issue by recycleroy** [mrvautin/expressCart#37]
After configuring product options, they don't appear correctly. No radio buttons or check boxes.
Also no way to add pricing for the options on a base product.

**Comment by reachdevelopers** [comment]
also after editing a product with options and you add a new option to the existing ones only the new option gets added and rest are deleted.

**Comment by mylastore** [comment]
both check boxes or radios don't save the values on add to cart. Well they add the wrong value not the selected ones.

**Comment by mylastore** [comment]
Was this fixed?

**Comment by mrvautin** [comment]
I can't replicate with very little information. Works fine for me.

**Comment by mylastore** [comment]
All values from radios, and select inputs don't save correctly. And if you have a select input and you unchecked it it throws an undefined error.

**Comment by mrvautin** [comment]
I'm running the latest version on Github and cannot reproduce this error. Can you please specify the exact steps? I've tried adding options of all types and get no errors.

**Comment by mylastore** [comment]
When a product is added to the cart all radio and select input values are wrong drop down are good

**Comment by mylastore** [comment]
By the way this is awesome finally an express cart been waiting for something like this for a while.

**Comment by mylastore** [comment]
![new-product](https://user-images.githubusercontent.com/8906338/52525039-8c0e4380-2c58-11e9-9464-fba5276db648.png)

![new-pro](https://user-images.githubusercontent.com/8906338/52525067-05a63180-2c59-11e9-8abc-68257b6ec84d.png)

add something to the cart with radios or select inputs

**Comment by mylastore** [comment]
cool  thank you sir
