### ISSUE TITLE
If images aren't done uploading it crashes the app

### ISSUE THREAD

**Issue by codypace68** [mrvautin/expressCart#38]
When in the admin page if you click upload image for a product and select your image, there is no prompt to let you know when the file is done uploading. If you click upload before the file is done uploading it will crash the app

**Comment by prabhatku304** [comment]
when I had uploaded the file ,it has successfull submited . no problem in this app and also no crash happened during uploading the file on app.check again

> When in the admin page if you click upload image for a product and select your image, there is no prompt to let you know when the file is done uploading. If you click upload before the file is done uploading it will crash the app

**Comment by mrvautin** [comment]
Cannot reproduce. Needs more info.
