### ISSUE TITLE
Product quantity for stock management 

### ISSUE THREAD

**Issue by nivalamata** [mrvautin/expressCart#40]
hi , I was checking  add product feature in admin dashboard,  I noticed there is no quantity field and I thought It would be nicer if  we manage stock and if product  is out of stock , we can put a label on product. so that user can know before hand.  I can do some PR if needed.

**Comment by mrvautin** [comment]
Added in 3ab76684bb371470cbd09bf7cc28390d0807d65b.

**Comment by mylastore** [comment]
I still don't see quantity when creating a new product.
<img width="891" alt="Screen Shot 2019-05-19 at 6 41 18 PM" src="https://user-images.githubusercontent.com/8906338/57991760-bfd1e400-7a65-11e9-82fe-40ad494f085b.png">

**Comment by mylastore** [comment]
never mind found it on settings.json
