### ISSUE TITLE
Rendering all the data from config to hbs engine

### ISSUE THREAD

**Issue by bharatiprashant** [mrvautin/expressCart#45]
while rending the page from  server end the login controller is exposing all the config file that can be accessed on clients end, that information contains smtp paswwords, db url, third party api's and all the highly sesitive data that should be protected.

exports.newUser=(req, res) => {
    res.render('user_new', {
        title: 'User - New',
        admin: req.session.isAdmin,
        session: req.session,
        helpers: req.handlebars.helpers,
        message: common.clearSessionValue(req.session, 'message'),
        messageType: common.clearSessionValue(req.session, 'messageType'),
        config: req.app.config
    })
}

**Comment by mrvautin** [comment]
huh? This info is not client side. I'm not sure what you mean.

**Comment by bharatiprashant** [comment]
while rendering the data in view why are we sending req.app.config? this file contains many sensitive data like email password, my database connection strings
