### ISSUE TITLE
Validation issue while adding item to Cart

### ISSUE THREAD

**Issue by nabaragpaul** [mrvautin/expressCart#46]
There is no server side checking or validation of number in qty field while adding item to cart.Or it doesn't even check the inventory for availability as well. User can edit maxlength from inspector console and can put any number without validation

**Comment by mrvautin** [comment]
It does both of those things. The only part which it doesn't do is track stock on concurrent carts. Eg: if there are 5 items in stock and two people have 3 each in their cart it will allow them both to checkout and pay.
