### ISSUE TITLE
Add to cart more then available stock on a product not working correctly

### ISSUE THREAD

**Issue by mylastore** [mrvautin/expressCart#47]
I added a product with 2 in stock and I was able to add 2 at a time to the cart with no issues.

**Comment by mrvautin** [comment]
Hmm yes I see what you mean. I will have a think on best way to tackle that.

**Comment by mylastore** [comment]
> Hmm yes I see what you mean. I will have a think on best way to tackle that.

thanks

**Comment by mylastore** [comment]
by clicking on add to cart button several times lets you add more then available stock qty. I fixed this on my local repo by hiding the add to cart and qty inputs when stock is 0.

**Comment by mrvautin** [comment]
This has been fixed in the latest version.
