### ISSUE TITLE
Enhancement UX , cart is not visible in smaller screen until menu button click

### ISSUE THREAD

**Issue by nivalamata** [mrvautin/expressCart#50]
![Screen Shot 2019-03-10 at 13 54 56](https://user-images.githubusercontent.com/1016547/54084046-ea544200-433c-11e9-8c80-88ad931f7383.png)

**Comment by mrvautin** [comment]
That’s the point of responsive design. If you want to change the theme you can add the cart link next to the menu icon. This is customisable using a theme.
