### ISSUE TITLE
How to add product in the subcategory?

### ISSUE THREAD

**Issue by hashitherock** [mrvautin/expressCart#51]
Hi,

First thanks for your expresscart.
I have downloaded your code.
Run in the localhost and I like it.
Now I want to create subcategory and add products in that subcategory.
How can I do that?

Thanks in Advance.

**Comment by mrvautin** [comment]
expressCart is search based and not category. You will need to add keywords to your product to make them easily searchable. You can also group with links like this where the category is `boots`:  https://demo.expresscart.markmoffat.com/category/boots
