### ISSUE TITLE
Product update cause crash

### ISSUE THREAD

**Issue by pteyssedre** [mrvautin/expressCart#66]
Hi,

I just setup a server with mongodb and expressCart, but each time i try to save a product the application crash which the following error

```
TypeError: common.indexProducts is not a function
    at db.products.update (/home/webmaster/expressCart/routes/product.js:256:36)
    at handleCallback (/home/webmaster/expressCart/node_modules/mongodb/lib/utils.js:96:12)
    at /home/webmaster/expressCart/node_modules/mongodb/lib/collection.js:1016:5
    at /home/webmaster/expressCart/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:405:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Everything else works perfectly. Any idea what I messed up ?
I'm using Ubuntu 14 with the mongodb provided by Ubuntu repos and the version of expressCart is the one from today

**Comment by mrvautin** [comment]
Should be fixed in 0972565124e88e2dc57744e72b8734ffc85d1532. Can you pull and confirm?

**Comment by mrvautin** [comment]
Note: I'm working on some refactoring to the routes and caused this bug in the current version.

**Comment by pteyssedre** [comment]
Sorry for the late notice but THANKS !! everything is working fine now
