### ISSUE TITLE
Feature-Request: Subscription Model

### ISSUE THREAD

**Issue by iamsvenh** [mrvautin/expressCart#68]
This project is amazing. I was wondering if you'd be willing to extend the functionality to include a Subscription bases E-Commerce store. Where users can subscribe to a recurring product. E.g food-subscription-boxes. Which can be either weekly, monthly, etc.

**Comment by mrvautin** [comment]
Work on this is underway. I will update here once complete. @Badmonky

**Comment by mrvautin** [comment]
Added in a87d2fbf0a920296da5f7cabd723d4ae6ec357ed.
