### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by afiali** [mrvautin/expressCart#7]
Hi.

How to add a product in a category?

**Comment by hashitherock** [comment]
Hi,

To add a product in a category:
Step 1: Add a Menu Name. Ex: menu field is "Grocery".
Step 2: Give Menu Link value is "/category/grocery".
Step 3: Add "Grocery" into Product tag words field in New product or Edit product Page.
Step 4: Save Product.

Thank you.

**Comment by quangvinh1305** [comment]
dear @hashi15 ,
I did like your instruction but it is not work.
![Screen Shot 2019-09-23 at 7 22 55 AM](https://user-images.githubusercontent.com/6763141/65396684-1021cf80-ddd3-11e9-9805-e55cb6fe8c1a.png)
Thanks,
