### ISSUE TITLE
How to group products by tags

### ISSUE THREAD

**Issue by quangvinh1305** [mrvautin/expressCart#80]
![Screen Shot 2019-09-23 at 7 32 52 AM](https://user-images.githubusercontent.com/6763141/65396807-65aaac00-ddd4-11e9-8cc0-9405ad87acc5.png)
![Screen Shot 2019-09-23 at 7 34 04 AM](https://user-images.githubusercontent.com/6763141/65396821-8c68e280-ddd4-11e9-833d-38937ba66232.png)
![Screen Shot 2019-09-23 at 7 33 41 AM](https://user-images.githubusercontent.com/6763141/65396823-94288700-ddd4-11e9-991b-6ee5839487f2.png)

I created Grocery and then create products with Grocery grocery tags. but when i choose link Grocery it is not work.

Thanks

**Comment by mrvautin** [comment]
Try restarting the app to check whether there is a problem indexing/reindexing the keywords.

**Comment by quangvinh1305** [comment]
Dear @mrvautin ,
i tried but nothing happened.

**Comment by Jamezslim90** [comment]
@quangvinh1305 

How were you able to log in to admin?

I TRIED TO LOG IN AFTER I SIGNED UP BUT IT FAILED TO SIGN IN
