### ISSUE TITLE
handlebars variable missing after call helper

### ISSUE THREAD

**Issue by rungsoso** [mrvautin/expressCart#82]
After call handlebars helper variable value is null

For example **cart.hbs** the **Pay now** button doesn't show because the {{page}} variable is null after call helper ( {{#ifCond page '!=' 'pay'}} ).

<div>before: {{page}}</div>
            {{#ifCond page '!=' 'pay'}}
            <div>after: {{page}}</div>
            <div class="text-right align-right col s6">
                {{#ifCond page '==' 'checkout'}}
                <a href="/pay" class="btn waves-effect waves-light blue darken-3">Pay now</a>
                {{else}}
                <a href="/checkout" class="btn waves-effect waves-light blue darken-3">Checkout</a>
                {{/ifCond}}
            </div>
            {{/ifCond}} {{/if}}

![1570181703333](https://user-images.githubusercontent.com/24908027/66197639-0185c300-e6c5-11e9-9a57-a59a14397d37.jpg)

**Comment by mrvautin** [comment]
I'm not sure what your issue is. Can you explain?

**Comment by mrvautin** [comment]
Fixed in 5a99d248ab3d66299c900ca7fdc3aeba24e8da75.
