### ISSUE TITLE
Products not shown on User Page even after adding them in Admin Panel

### ISSUE THREAD

**Issue by Smackrush** [mrvautin/expressCart#85]
I am able to add products successfully in Admin Panel and It is showing on list.

But when I connect http://localhost:1111/ , It shows 'No products found'. I am not getting the way how to import those products into User Interface or am I missing something?

![Screen Shot 2019-10-15 at 5 03 20 PM](https://user-images.githubusercontent.com/56589322/66828149-f3119400-ef6d-11e9-98c1-ccc95ae006a3.png)
![Screen Shot 2019-10-15 at 5 03 57 PM](https://user-images.githubusercontent.com/56589322/66828166-fb69cf00-ef6d-11e9-94cd-f4f215f649f5.png)

**Comment by kurozael** [comment]
I am also experiencing this problem.
