### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [mrvautin/expressCart#86]
This project has a security vulnerability. Please open an advisory and add me.
https://github.com/mrvautin/expressCart/security/advisories

**Comment by mrvautin** [comment]
Fixed 3c9a86306a1ea5d633ecf84690d1951a2b63ab17.

**Comment by JLLeitschuh** [comment]
@mrvautin Can you re-open the advisory so we can finish it out and get this issue disclosed.
