### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by anddimario** [mrvautin/expressCart#87]
I'm thinking to a very basic multi language system, i thought to use a handblebar helper for translation in the view. Admin can edit languages in a json format from a dedicated backoffice section. Translationts are stored on mongo and on layout.hbs a widget for language switcher.

What do you think about that?

**Comment by mrvautin** [comment]
I'd be more keen on using a module like this: https://www.npmjs.com/package/i18n-2 and storing data in language files.

**Comment by anddimario** [comment]
ok, storage on db could be avoid app reload. I'll see how your link works, it seems a rapid implemetations for express

**Comment by anddimario** [comment]
Merged, so i close this :)
