### ISSUE TITLE
Footer HTML does not display

### ISSUE THREAD

**Issue by kurozael** [mrvautin/expressCart#89]
I have edited the footer HTML but nothing is displaying. The "Powered by expressCart" does hide itself though for some reason.

**Comment by mrvautin** [comment]
Can you give an example? A screenshot?

**Comment by kurozael** [comment]
Hey @mrvautin, you can find the test website [here](https://store2.cloudsixteen.com/) where you can see no footer being displayed, despite having custom footer HTML set in the config.

**Comment by mrvautin** [comment]
Could you post your settings.json file?
