### ISSUE TITLE
Scrollbar on mobile displays when using hamburger menu

### ISSUE THREAD

**Issue by kurozael** [mrvautin/expressCart#90]
![image](https://user-images.githubusercontent.com/486972/67753099-19363a00-fa2c-11e9-9fe9-470d7951585d.png)

As you can see, when using a mobile display size, the hamburger menu opens with a scrollbar. It would be good if the expanded menu a) animated to its maximum size and b) did not have a scrollbar but instead expanded so that all items contained within it would fit nicely inside.

Thanks for the hard work @mrvautin 👍

**Comment by mrvautin** [comment]
I can confirm I see the same. Looks to be an issue with the Theme CSS. I will fix it when I get some time. I'd welcome a PR if you can fix it sooner.
