### ISSUE TITLE
Changing config in the admin panel seems to require a restart of the Node app

### ISSUE THREAD

**Issue by kurozael** [mrvautin/expressCart#92]
Unless this is just occurring for me for some reason, would it be possible for configuration to be refreshed dynamically without restarting the whole app? To be investigated...

I may look into this myself if I get some time over the weekend.

**Comment by mrvautin** [comment]
Should be fixed in 9f1eca7b025e490a861e7e7cf6827b49479802a3.

**Comment by kurozael** [comment]
Brilliant, thanks!
