### ISSUE TITLE
Users improvements

### ISSUE THREAD

**Issue by anddimario** [mrvautin/expressCart#93]
It could be useful improve users, maybe with employee, and allow user login and dashboard features (it could be useful for https://github.com/mrvautin/expressCart/issues/68)

**Comment by mrvautin** [comment]
I've been working on #68 for a bit and its almost finished.

**Comment by MukeshSinghBisht** [comment]
I was looking for opportunity to contribute, I am kind of naive in this. I wanted to figure out what is the exact issue in #93. can somebody guide me through this, it will be extremely helpful.

**Comment by mrvautin** [comment]
This functionality has been added and this issue can be closed.
