### ISSUE TITLE
Can't connect to Mongodb Atlas

### ISSUE THREAD

**Issue by peterpans2013** [mrvautin/expressCart#94]
I got this error: "settings.json incorrect: data.databaseConnectionString should match format "uri-template"" while trying to connect with Mongodb Atlas.
Can you help me with it or can you tell me how to connect this app with Mongodb Atlas.
Thanks

**Comment by peterpans2013** [comment]
Or can you tell me how to run this app without connecting to DB.
I just want to try the front end of this app.
Thanks

**Comment by mrvautin** [comment]
You can’t run the app without a DB. Can you supply the connection string (replacing username and password)? It’s likely the validation of the `settings.json` doesn’t cater for new connection strings.

**Comment by peterpans2013** [comment]
this is my connection string from Mongodb Atlas
"mongodb+srv://King:<Anhchien01>@cluster0-al5gu.gcp.mongodb.net/test?retryWrites=true&w=majority"
