### ISSUE TITLE
Issue faced on deploying on aws

### ISSUE THREAD

**Issue by vikashanand** [mrvautin/expressCart#99]
Hi, 

I have deployed the same on AWS. I am able to access the application locally on AWS EC2 instance but I am not able to access the application from my desktop using the instance public ip.

**Comment by mrvautin** [comment]
I’m not sure how you think this is a `expressCart` issue? This seems related to AWS.

**Comment by vikashanand** [comment]
Agreed :) 
Code is running on aws local IP. But not accessable from public IP although the port is enabled. Is it something to do with host? FYI.. I am running my code on EC2 rather than deploying on EC2.
